color=input("Hey there! What's your favorite color?")
print('Great Choice! '+color+ ' is an awesome color!')
if color=="red": print('My favorite color is red too!') 
elif color=="Red": print('My favorite color is red too!')
else: print('My favorite color is red.')
input ("Goodbye!")