print ("Hello! In order to assemble your company ID, we would like you to answer the following questions:")
Firstname=input ("What is your first name?")
Lastname=input ("What's your last name?")
Email=input ("What's your professional email adress?")
Phone=input ("What's your phone number?")
JobTitle=input ("What current job title do you have?")
Month=input ("What month did you start working for the company?")
Training=input("Have you undergone any sort of professional training for your position?")
Hair=input("Lastly, in order to identify you personally, we'd like to know your hair color.")
Eye=input ("You're almost done! What is your eye color?")
IDNumber=input("Last question, for real this time! What is your employee ID number?")
print ("Processing, please wait.")
import time
time.sleep(5)
print("Here is your official, company ID!:")
print("-----------------------------------------------------------")
print (f"{Lastname.upper()}, {Firstname.capitalize()}")
print(JobTitle.title())
print("ID: "+IDNumber)
print("")
print(Email.lower())
print(Phone)
print(" ")
print(f"Hair Color: {Hair:15} Eye Color: {Eye}")
print(f"Month Started: {Month:10} Training Achomplished: {Training}")
print("-----------------------------------------------------------")
