print("Please enter the following words, to assemble your unique story.")
adjective= input("Adjective:")
adverb= input("Adverb:")
verb= input("Verb, in past tense:")
object= input("Object:")
Animal= input("Animal:")
secondverb= input("2nd Verb, in past tense:")
location= input("Place(keep it vague, such as park, hospital, school, mountain, house, etc.):")
job= input("Title(examples: firefighter, policeman, nurse, etc.):")
thirdverb= input("3rd Verb, in past tense:")
print("Okay, here's your story!:")
print("----------------------------------------------------------------")
print ("One day when I was walking down the street, I saw something very strange. A "+adjective.lower()+" gorilla was "+adverb.lower()+" bounding down the street. When it saw me, it raised it's fists, and "+verb.lower()+"! Then, it charged toward me, picking up a "+object.lower()+" as it went, and throwing it at me. As I dodged it, I noticed a "+Animal.lower()+" running by! I absolute fear, I "+secondverb.lower()+" to the nearest "+location.lower()+" to seek aid from the local "+job.lower()+". They ran out with me to calm the gorilla and the "+Animal.lower()+". The "+job.lower()+" stepped forward, and calmly "+thirdverb.lower()+". And everything was okay all of the sudden. It was a really wierd day!")
print("----------------------------------------------------------------")
input("")
print("Arizona is Amazing!")
